export const chatsTypes = {
  FETCH_CHAT_START: "FETCH_CHAT_START",
  FETCH_CHAT_SUCCESS: "FETCH_CHAT_SUCCESS",
  FETCH_CHAT_FAILUER: "FETCH_CHAT_FAILUER",
  APPEND_CHAT: "APPEND_CHAT",
  SET_CURRENT_CHAT: "SET_CURRENT_CHAT",
  DELETE_MSG: "DELETE_MSG",
  UPLOADING_FILE: "UPLOADING_FILE",
  UPLOADING_FILE_SUCCESS: "UPLOADING_FILE_SUCCESS",
  UPLOADING_FILE_FAILED: "UPLOADING_FILE_FAILED",
  RESET_UPLOAD: "RESET_UPLOAD",
};
