export const chatListTypes = {
  FETCH_CHAT_LIST_START: "FETCH_CHAT_LIST_START",
  FETCH_CHAT_LIST_SUCCESS: "FETCH_CHAT_LIST_SUCCESS",
  FETCH_CHAT_LIST_FAILURE: "FETCH_CHAT_LIST_FAILURE",
  FIND_USERS_START: "FIND_USERS_START",
  FIND_USERS_SUCCESS: "FIND_USERS_SUCCESS",
  FIND_USERS_FAILED: "FIND_USERS_FAILED",
};
