export const userTypes = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
  LOGIN_FAILED: "LOGIN_FAILED",
  SIGNUP_START: "SIGNUP_START",
  SIGNUP_SUCCESSFUL: "SIGNUP_SUCCESSFUL",
  SIGNUP_FAILED: "SIGNUP_FAILED",
  LOGOUT_SUCCESSFUL: "LOGOUT_SUCCESSFUL",
  LOGOUT_FAILED: "LOGOUT_FAILED",
  UPDATE_SUCCESSFUL: "UPDATE_SUCCESSFUL",
  UPDATE_FAILED: "UPDATE_FAILED",
  UPDATING: "UPDATING",
};
